- Working on some setup-disk hacks

diff --git a/src/unity-conf/setup-bootable.in b/src/unity-conf/setup-bootable.in
--- a/src/unity-conf/setup-bootable.in
+++ b/src/unity-conf/setup-bootable.in
@@ -393,7 +393,7 @@ fi
 echo "Making $dest bootable..."
 
 if ! [ -x "$(which syslinux)" ]; then
-	yum install --quiet syslinux || die "Failed to install syslinux"
+	yum install -y syslinux || die "Failed to install syslinux"
 	uninstalls="syslinux"
 fi
 
